parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\UserInterface\Web\Controller\:
        resource: '../src/UserInterface/Web/Controller'
        tags: ['controller.service_arguments']
